Correct OTA build
cmm-apps-android/EsmorgaAndroid pull request #30
Opened 2024-09-13 07:36 UTC by pablomarinoacn

2024-09-13 14:17 UTC, andreslopezsarmiento requested changes

2024-09-13 14:17 UTC, andreslopezsarmiento commented on .github/workflows/WhenMainChange.yml
> +  #Delete this , just for test
delete this

2024-09-13 14:17 UTC, andreslopezsarmiento commented on .github/actions/buildAndUpload/action.yaml
> +        visibleClient=true
is this line duplicated?

2024-09-13 14:19 UTC, pablomarinoacn commented on .github/workflows/WhenMainChange.yml
> +  #Delete this , just for test
👍

2024-09-13 14:19 UTC, pablomarinoacn commented on .github/actions/buildAndUpload/action.yaml
> +        visibleClient=true
fuck

2024-09-16 11:25 UTC, andreslopezsarmiento approved these changes

2024-09-16 11:29 UTC, merged